-- =====================================================================
-- KORA — pending migrations for the staging/production Supabase project
-- Generated by auditing the LIVE schema, not the file list: these five are
-- the ones whose tables/columns are genuinely absent. The other fourteen
-- migrations in backend/migrations/ are already applied.
--
-- Paste the whole thing into the Supabase SQL editor and run once.
-- Safe to re-run: every statement is guarded (IF NOT EXISTS, and policies
-- are dropped before being recreated — CREATE POLICY has no IF NOT EXISTS).
--
-- Order matters: gdpr_compliance creates deletion_log, and the migration
-- after it adds a column to that table.
-- =====================================================================


-- ==================== 2026-06-19_invoice_enhancements.sql ====================
-- Migration: Invoice enhancements (invoice_artifact)
-- New columns on invoices, users, clients for professional PDF + real email delivery.
-- All columns are nullable — backward-compatible with existing data.
-- Run once in the Supabase SQL editor before using KORA_DATA_BACKEND=supabase.

-- ── Invoice table additions ──────────────────────────────────────────────────

ALTER TABLE invoices ADD COLUMN IF NOT EXISTS invoice_date DATE;
-- Backfill:
-- UPDATE invoices SET invoice_date = created_at::date WHERE invoice_date IS NULL;

ALTER TABLE invoices ADD COLUMN IF NOT EXISTS payment_terms TEXT;
-- "Net 14", "Net 30", "Due on receipt", etc.

ALTER TABLE invoices ADD COLUMN IF NOT EXISTS payment_terms_days INTEGER;

ALTER TABLE invoices ADD COLUMN IF NOT EXISTS client_address TEXT;

ALTER TABLE invoices ADD COLUMN IF NOT EXISTS client_tax_id TEXT;

ALTER TABLE invoices ADD COLUMN IF NOT EXISTS po_number TEXT;

ALTER TABLE invoices ADD COLUMN IF NOT EXISTS pdf_path TEXT;

ALTER TABLE invoices ADD COLUMN IF NOT EXISTS email_message_id TEXT;

ALTER TABLE invoices ADD COLUMN IF NOT EXISTS amount_paid NUMERIC(12,2) DEFAULT 0;

-- ── User additions (sender address on invoices) ──────────────────────────────

ALTER TABLE users ADD COLUMN IF NOT EXISTS business_address TEXT;

ALTER TABLE users ADD COLUMN IF NOT EXISTS tax_id TEXT;

ALTER TABLE users ADD COLUMN IF NOT EXISTS invoice_footer TEXT;

-- ── Client table additions ────────────────────────────────────────────────────

ALTER TABLE clients ADD COLUMN IF NOT EXISTS billing_address TEXT;

ALTER TABLE clients ADD COLUMN IF NOT EXISTS tax_id TEXT;

-- ── agent_logs agent_type CHECK — extend for email delivery ─────────────────
-- email_service.py logs 'email_delivery' (invoice send) and 'morning_digest'.
-- Run only if agent_logs has the strict CHECK constraint.

ALTER TABLE agent_logs DROP CONSTRAINT IF EXISTS agent_logs_agent_type_check;
ALTER TABLE agent_logs ADD CONSTRAINT agent_logs_agent_type_check
    CHECK (agent_type IN (
        'bookkeeper','invoice_follow_up','contract_generator','cashflow_forecaster',
        'alert_generator','cross_module','supervisor','chat','butler','butler_gmail',
        'butler_drive','butler_calendar','meeting_agent','gmail_agent','calendar_agent',
        'playbook','email_delivery','morning_digest'
    ));

-- ==================== 2026-07-23_add_client_view_cache.sql ====================
-- Migration: client_view_cache (M3 — PM agent fan-out)
-- The agent-composed one-pager per client. Four role-scoped analysts run in
-- parallel, a DETERMINISTIC code merge assembles their prose around
-- ground-truth numbers, and the result is cached here so a page load costs
-- ZERO LLM calls (invariant client_view_refresh_is_cached).
--
-- Design notes:
--  * Keyed by (user_id, client_id) — one current view per client. A refresh
--    upserts; GET reads. No history kept (the ledger is the source of truth;
--    this is a derived, disposable cache).
--  * `view` holds the composed sections + headline metrics; `token_cost` holds
--    the measured fan-out spend so the budget gate is observable in prod.
--  * ON DELETE CASCADE on both FKs: a cached view is meaningless once its
--    client (or user) is gone.
--
-- Run against Supabase before using the client view in KORA_DATA_BACKEND=supabase.

CREATE TABLE IF NOT EXISTS client_view_cache (
    user_id      UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    client_id    UUID NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
    view         JSONB NOT NULL DEFAULT '{}'::jsonb,
    token_cost   JSONB NOT NULL DEFAULT '{}'::jsonb,
    refreshed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, client_id)
);

CREATE INDEX IF NOT EXISTS idx_client_view_user ON client_view_cache (user_id);

ALTER TABLE client_view_cache ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users access own client views" ON client_view_cache;
CREATE POLICY "Users access own client views"
    ON client_view_cache FOR ALL
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

-- ==================== 2026-07-29_gdpr_compliance.sql ====================
-- M9 — GDPR/CCPA compliance infrastructure.
--
-- (1) deletion_log: append-only audit table proving a deletion request was
--     honored. Intentionally carries NO PII and NO user_id FK — the request id
--     is a random UUID so even correlation with timing windows is bounded.
--     RLS disabled because there is no tenant to scope to: writes happen via
--     the service-role key, and no read path exists for this table from the
--     app surface.
--
-- (2) users.consent_version + users.consent_given_at: capture the policy
--     version the user agreed to and when. Defaults are NULL until the user
--     finishes onboarding or hits POST /api/account/consent.

-- ── (1) deletion_log ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.deletion_log (
  id           UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  deleted_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  reason       TEXT NOT NULL DEFAULT 'user_request',
  -- Aggregated counts so the audit row is self-describing. No row data.
  tables_cleared      JSONB NOT NULL DEFAULT '{}'::jsonb,
  files_deleted_count INTEGER NOT NULL DEFAULT 0,
  user_request_id     UUID NOT NULL DEFAULT uuid_generate_v4()
);

COMMENT ON TABLE public.deletion_log IS
  'Append-only GDPR/CCPA audit. No PII, no user_id FK. '
  'See .genesis/checkpoints/M9.md.';

-- ── (2) users.consent_* ─────────────────────────────────────────────────────
ALTER TABLE public.users
  ADD COLUMN IF NOT EXISTS consent_version   TEXT,
  ADD COLUMN IF NOT EXISTS consent_given_at  TIMESTAMPTZ;

COMMENT ON COLUMN public.users.consent_version  IS 'Policy version the user agreed to (e.g. 2026-06-01).';
COMMENT ON COLUMN public.users.consent_given_at IS 'Timestamp of the most recent consent capture.';

-- ==================== 2026-07-31_deletion_log_side_effects.sql ====================
-- M9 follow-up — persist the per-side-effect outcome map on the deletion audit.
--
-- The GDPR erasure endpoint runs several best-effort steps (Google token
-- revoke, Stripe cancel, GCS wipe, auth-identity delete). Recording their
-- outcomes makes the audit row actually able to prove WHAT happened, not just
-- that a request came in. Values are status strings only (e.g. "revoked",
-- "not_applicable: no subscription", "failed: TimeoutError") — NO PII, keeping
-- deletion_log's no-PII contract intact.
--
-- Backward-compatible: `record_deletion` writes this column when present and
-- silently falls back to the old row shape if the migration hasn't been applied.

ALTER TABLE public.deletion_log
  ADD COLUMN IF NOT EXISTS side_effects JSONB NOT NULL DEFAULT '{}'::jsonb;

COMMENT ON COLUMN public.deletion_log.side_effects IS
  'Per-step erasure outcomes (status strings only, no PII): '
  'google_revoke, stripe_cancel, gcs_delete, auth_delete, deletion_log.';

-- ==================== 2026-07-31_import_jobs.sql ====================
-- M8 (R1) — durable background-import job state.
--
-- CSV import runs as a background task; the frontend polls its status. The
-- status lived in a per-process in-memory dict, so under >1 worker the poll
-- could hit a worker that never ran the job → a permanent 404 for an import
-- that actually succeeded, and all state was lost on restart. Persisting the
-- job makes status shared across workers and durable across restarts.
--
-- Rows carry no PII (status + aggregate counts). ON DELETE CASCADE from
-- auth.users cleans them up when an account is erased (GDPR).

CREATE TABLE IF NOT EXISTS public.import_jobs (
  id          TEXT PRIMARY KEY,
  user_id     UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  status      TEXT NOT NULL DEFAULT 'pending',   -- pending | processing | done | error
  result      JSONB NOT NULL DEFAULT '{}'::jsonb, -- inserted/duplicatesSkipped/… on success
  error       TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_import_jobs_user
  ON public.import_jobs (user_id, created_at DESC);

-- Defense-in-depth (the app already filters by user_id via the repo() wrapper).
ALTER TABLE public.import_jobs ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'import_jobs'
      AND policyname = 'Users see own import jobs'
  ) THEN
    DROP POLICY IF EXISTS "Users see own import jobs" ON public.import_jobs;
CREATE POLICY "Users see own import jobs"
    ON public.import_jobs
      FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;
