import { LegalShell, H2, P, UL, Callout } from '@/components/legal/legal-shell';

export const metadata = {
  title: 'Terms of Service — Kora',
  description: 'The terms governing your use of Kora.',
};

export default function TermsPage() {
  return (
    <LegalShell title="Terms of Service" updated="May 30, 2026">
      <P>
        These Terms of Service (&quot;Terms&quot;) govern your access to and use of Kora. By creating an account
        or using the service, you agree to these Terms.
      </P>

      <H2>1. The service</H2>
      <P>
        Kora is an AI-assisted back-office platform for freelancers and small businesses, providing
        bookkeeping, invoicing, cash-flow forecasting, and document generation. Features may change as the
        product evolves.
      </P>

      <H2>2. AI-generated content disclaimer</H2>
      <Callout>
        Contracts, financial reports, and other content generated by Kora are produced by AI and are provided
        for informational purposes only. They do not constitute legal, tax, or financial advice. Kora is not
        liable for decisions made based on AI-generated content. Always review important documents and consult
        a qualified professional where appropriate.
      </Callout>

      <H2>3. Your responsibilities</H2>
      <UL
        items={[
          'Provide accurate account and business information.',
          'Keep your login credentials secure and confidential.',
          'Use the service lawfully and only for businesses you are authorized to manage.',
          'Review AI-generated documents and figures before relying on them.',
        ]}
      />

      <H2>4. Payment and refunds</H2>
      <P>
        Paid plans are billed in advance on a recurring basis through our payment processor. You may cancel at
        any time; cancellation stops future renewals and takes effect at the end of the current billing period.
        Except where required by law, fees already paid are non-refundable.
      </P>

      <H2>5. Account termination</H2>
      <P>
        You may close your account at any time. We may suspend or terminate accounts that violate these Terms,
        misuse the service, or create security or legal risk. On termination, your data is handled as described
        in our{' '}
        <a href="/privacy" className="text-kora-600 hover:underline">Privacy Policy</a>.
      </P>

      <H2>6. Limitation of liability</H2>
      <P>
        To the maximum extent permitted by law, Kora&apos;s total liability arising out of or relating to the
        service is limited to the amount of subscription fees you paid in the three (3) months preceding the
        event giving rise to the claim. The service is provided &quot;as is&quot; without warranties of any kind.
      </P>

      <H2>7. Governing law</H2>
      <P>
        These Terms are governed by the laws of the jurisdiction in which Kora is established, without regard to
        conflict-of-law principles. Disputes will be resolved in the courts of that jurisdiction.
      </P>

      <Callout>
        These Terms are provided as a clear baseline for the Kora MVP and are not a substitute for tailored
        legal advice. Have them reviewed by qualified counsel before commercial launch.
      </Callout>

      <H2>8. Contact</H2>
      <P>
        Questions about these Terms? Contact{' '}
        <a href="mailto:privacy@kora.app" className="text-kora-600 hover:underline">privacy@kora.app</a>.
      </P>
    </LegalShell>
  );
}
